language: android

jdk: oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools # appears twice as per Travis docs

    # The BuildTools version used by your project
    - build-tools-26.0.2
    #- build-tools-27.0.3 # latest build-tools ver doesn't work well with travis

    # The SDK version used to compile your project
    - android-26 # android 8.0
    - android-22 # used for emulator

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
    - extra-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  # Create and start emulator (used to run automated tests)
  - android list targets
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  #- while [[ `adb shell pm path android` == 'Error'* ]]; do sleep 2; done
  - adb shell input keyevent 82 &

      # Uncomment and specify the correct key
      # for integration into Slack 
#notifications:
  #slack: ict2105:PNXMGobtKXUUl2Gvq3jVhyU0